version: "3"

services:
  web:
    image: newstorycontainerregistry.azurecr.io/api:latest
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - redis
  worker:
    image: newstorycontainerregistry.azurecr.io/celery-queue:latest
    environment:
      - USER
      - PASSWORD
    depends_on:
      - redis
  monitor:
    image: newstorycontainerregistry.azurecr.io/celery-queue:latest
    ports:
      - "5555:5555"
    entrypoint: flower
    command: -A tasks --port=5555 --broker=redis://redis:6379/0 --basic_auth=${FLOWER_USER:?err}:${FLOWER_PASSWORD:?err}
    depends_on:
      - redis
  redis:
    image: redis