version: "3"
services:
  web:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/bitnami/express:4-debian-10'
    command: npm run dev-docker
    environment:
      - PORT=3000
      - NODE_ENV=development
      - SKIP_NPM_INSTALL=0
      - VAR=2
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - FLOWER_URL=http://monitor:5555
      - AZURE_STORAGE_CONNECTION_STRING
      - CONTAINER_NAME
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    depends_on:
      - redis
  profile_worker:
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - AZURE_STORAGE_CONNECTION_STRING
      - CONTAINER_NAME
      - WORKER=1
      - PROXY_USER
      - PROXY_PASSWORD
      - PROXY_HOST
      - PROXY_PORT
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    entrypoint: celery
    command: -A src worker --loglevel=info --concurrency 1 -Q profile
    volumes:
      - D:/tmp/newstory/profiles:/tmp/profiles
    depends_on:
      - redis
  upload_worker:
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - AZURE_STORAGE_CONNECTION_STRING
      - CONTAINER_NAME
      - WORKER=1
      - PROXY_USER
      - PROXY_PASSWORD
      - PROXY_HOST
      - PROXY_PORT
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    entrypoint: celery
    command: -A src worker --loglevel=info --concurrency 1 -Q upload
    volumes:
      - D:/tmp/newstory/profiles:/tmp/profiles
    depends_on:
      - redis
  monitor:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL
    entrypoint: ./start_flower.sh
    depends_on:
      - redis
  redis:
    image: redis:6.0.8
