version: "3"
services:
  web:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/bitnami/express:4-debian-10'
    command: npm run dev-docker
    environment:
      - PORT=3000
      - NODE_ENV=development
      - SKIP_NPM_INSTALL=0
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - AZURE_STORAGE_CONNECTION_STRING
      - CONTAINER_NAME
    ports:
      - 3030:3000
    volumes:
      - ./web:/app
  profile_worker:
    environment:
      - AZURE_STORAGE_CONNECTION_STRING
      - CONTAINER_NAME
      - PROXY_USER
      - PROXY_PASSWORD
      - PROXY_HOST
      - PROXY_PORT
    build:
      context: worker
    volumes:
      - C:/tmp/newstory/profiles:/tmp/profiles
    depends_on:
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock