apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: newstorycontainerregistry.azurecr.io/web:latest
        ports:
        - containerPort: 3000
        env:
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: azure-data
                key: azure_storage_connection_string
          - name: CONTAINER_NAME
            valueFrom:
              secretKeyRef:
                name: azure-data
                key: container_name