name: Pre-commit

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master
      - name: pre-commit
        uses: pre-commit/action@v2.0.0
